### ISSUE TITLE
API inconsistency

### ISSUE THREAD

**Issue by aurel-l** [ProteinsWebTeam/interpro7-api#1]
Problem with the number of proteins returned depending on the endpoint:
/api/structure/pdb/1JM7/protein/ -> 2 👍🏻
/api/structure/pdb/1JM7/A/protein/ -> 1 👍🏻
/api/structure/pdb/1JM7/protein/uniprot/ -> 2 👍🏻
/api/structure/pdb/1JM7/A/protein/uniprot/ -> 2 👎🏻 (not filtering out chain B)

It seems that the filtering by chain is done for the counting (.../protein/) but not when returning the actual list (.../protein/uniprot/)

**Comment by 4ndr01d3** [comment]
Solved.
The filter of the View in charge of the structure chain wasn't considering the [endpoint]/[db] case.
