### ISSUE TITLE
API entry/interpro/protein/uniprot/ appears to be mostly broken 

### ISSUE THREAD

**Issue by GLHolliday79** [ProteinsWebTeam/interpro7-api#13]
Not sure if I'm trying to use this before it's "ready" but the API query: https://www.ebi.ac.uk/interpro/beta/api/entry/interpro/protein/uniprot/Q8A7T2
seems to just return an error.

```
HTTP 404 Not Found
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
InterPro-Version: 71.0
Vary: Accept
{
    "Error": "aggregations"
}
```
I've tried the example from the NAR DB paper (O00220) and it produces the same error. As do half a dozen other UniProt accession's I've tried.
Please advise?

**Comment by gustavo-salazar** [comment]
Hey there,
Sorry I only saw this issue now. The URL you mentioned seems to be working now.
Closing the issue now, and apologies again for such a horrible delay.
