### ISSUE TITLE
Question about retrieving residue-matching information on API

### ISSUE THREAD

**Issue by LongHung-Pham** [ProteinsWebTeam/interpro7-api#138]
Dear the InterPro team,

Thank you for developing this excellent database. I have a question about downloading the residue-position-matching in the .tsv file of UniProt entries.

If I go to an entry page, for example: https://www.ebi.ac.uk/interpro/protein/unreviewed/A0A125YJN6/ and click on "Download tsv file", the results give me the desired column "Matches" (the last column)

> Accession	Name	Source Database	Type	Integrated Into	Integrated Signatures	GO Terms	Protein Accession	Protein Length	Matches
cd00403	Ribosomal_L1	cdd	domain	IPR028364			a0a125yjn6	217	9..215
G3DSA:3.30.190.20		cathgene3d	homologous_superfamily				a0a125yjn6	217	22..64,155..211
G3DSA:3.40.50.790		cathgene3d	homologous_superfamily	IPR016095			a0a125yjn6	217	65..154

But if I use the generated API call link: [https://www.ebi.ac.uk:443/interpro/api/entry/all/protein/unreviewed/A0A125YJN6/](https://www.ebi.ac.uk/interpro/api/entry/all/protein/unreviewed/A0A125YJN6/), the result doesn't have that "Matches" column anymore:

> Accession	Name	Source Database	Type	Integrated Into	Integrated Signatures	GO Terms
cd00403	Ribosomal_L1	cdd	domain	IPR028364		
G3DSA:3.30.190.20		cathgene3d	homologous_superfamily			
G3DSA:3.40.50.790		cathgene3d	homologous_superfamily	IPR016095

Is there any way I can retrieve that residue-matching information on API for a UniProt entry? Thank you very much and I would very much appreciate your help.

**Comment by gustavo-salazar** [comment]
Hello there,
Sorry for the delayed response.
The JSON in the API call that you are mentioning (https://www.ebi.ac.uk/interpro/api/entry/all/protein/unreviewed/A0A125YJN6/) includes the data about matches but in a structured way. See the `entry_protein_locations` attribute on each protein.

There is a tool to generate example code to query our API, here is a link with your example: https://www.ebi.ac.uk/interpro/result/download/#/entry/InterPro/protein/unreviewed/A0A125YJN6/|tsv

You can edit the provided snippet to make sure of generating a matches column in the way you want it.

**Comment by LongHung-Pham** [comment]
Thank you very much for your reply, this helped me solve my problem now.
