### ISSUE TITLE
API timeout for IPR042099

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-api#15]
https://www.ebi.ac.uk/interpro/beta/api/entry/InterPro/IPR042099 returns. yet https://www.ebi.ac.uk/interpro/beta/api/entry/InterPro/IPR042099/protein/UniProt returns in ~1 second with 'Query timed out'

**Comment by gustavo-salazar** [comment]
Such shorts timeouts happen when the query takes longer than 90 secs the first time... The original query keeps running even if it times out, so whenever that finishes the response is loaded in the cache for future requests
https://github.com/ProteinsWebTeam/interpro7-api/tree/dev/webfront/views#cache-strategy
