### ISSUE TITLE
Pre-calculate taxonomy trees for entries

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-api#21]
Probably best to store the taxonomy tree in MySQL in json format

**Comment by gustavo-salazar** [comment]
PR #23 has been merge in dev and has been deployed to our dev machine: 
Example:
http://wp-np3-ad.ebi.ac.uk/interpro/api/taxonomy/uniprot/1?filter_by_entry=IPR001165
http://wp-np3-ad.ebi.ac.uk/interpro/api/taxonomy/uniprot/1?filter_by_entry_db=interpro

**Comment by gustavo-salazar** [comment]
deployed in live:
https://www.ebi.ac.uk/interpro/api/taxonomy/uniprot/1?filter_by_entry=IPR001165
