### ISSUE TITLE
MobiDB predictions in Interpro vs Interproscan export?

### ISSUE THREAD

**Issue by ewallace** [ProteinsWebTeam/interpro7-api#74]
How do I download MobiDB Lite disorder predictions from Interpro entries?

I'm asking because the Interpro entry for [my protein of interest, J9VWG0](https://www.ebi.ac.uk/interpro/protein/unreviewed/J9VWG0/) shows a MobiDB Lite consensus disorder predictions.  Yet when I download my .tsv file, other domains (e.g. SMART) are there but the MobiDB Lite prediction is missing.

Looking in more detail at [the API page for J9VWG0](https://www.ebi.ac.uk/interpro/api/entry/all/protein/unreviewed/J9VWG0/), I still didn't see an option to download the MobiDB Lite predictions.

However, if I scan the same protein at InterProScan, then press Export, it does output a .tsv including the MobiDB Lite predictions:

- [saved results, expire 2021-12-28](https://www.ebi.ac.uk/interpro/result/InterProScan/iprscan5-R20211221-085338-0951-80203306-p2m/)
- [InterProScan link used to generate those results was from FungiDB page for J9VWG0](https://fungidb.org/fungidb/app/record/gene/CNAG_01551#category:protein-properties)

How could I just download the MobiDB Lite predictions, with everything else or without, from the existing InterPro page?

Apologies if I missed anything obvious, and thank you for your wonderful work sharing data with the community!

**Comment by matthiasblum** [comment]
Hi,

Sorry for the late reply.

The API page you linked is the following: https://www.ebi.ac.uk/interpro/api/entry/all/protein/unreviewed/J9VWG0/.

This URL returns all entries (`entry/all`) matching J9VWGO (`protein/unreviewed/J9VWG0`). Entries are either InterPro entries, or member database signatures (i.e. the models integrated into InterPro entries).

Annotations from MobiDB Lite, TMHMM. Phobius, and SignalP are not considered entries as they are never integrated into InterPro entries. Therefore, they are not returned by the link above.

To retrieve these annotations, you can use the following link: https://www.ebi.ac.uk/interpro/api/protein/unreviewed/J9VWG0/?extra_features.

**Comment by ewallace** [comment]
Thank you Matthias,
That solves my problem of how to download the data, however, it means I'd have to download 2 separate files in order to analyse the displayed annotations locally.

Can I suggest you add this information to at least one of the [Interpro FAQs](https://www.ebi.ac.uk/interpro/help/faqs/), and the [API docs](https://github.com/ProteinsWebTeam/interpro7-api/tree/master/docs). I didn't see it in either place.
